export const States = [
   {name: 'Andhra Pradesh', id: 'AndhraPradesh'},
   {name: 'Arunachal Pradesh', id: 'ArunachalPradesh'},
   {name: 'Assam', id: 'Assam'},
   {name: 'Bihar', id: 'Bihar'},
   {name: 'Chhattisgarh', id: 'Chhattisgarh'},
   {name: 'Delhi', id: 'Delhi'},
   {name: 'Goa', id: 'Goa'},
   {name: 'Gujarat', id: 'Gujarat'},
   {name: 'Haryana', id: 'Haryana'},
   {name: 'Himachal Pradesh', id: 'HimachalPradesh'},
   {name: 'Jharkhand', id: 'Jharkhand'},
   {name: 'Karnataka', id: 'Karnataka'},
   {name: 'Kerala', id: 'Kerala'},
   {name: 'Madhya Pradesh', id: 'MadhyaPradesh'},
   {name: 'Maharashtra', id: 'Maharashtra'},
   {name: 'Manipur', id: 'Manipur'},
   {name: 'Meghalaya', id: 'Meghalaya'},
   {name: 'Mizoram', id: 'Mizoram'},
   {name: 'Nagaland', id: 'Nagaland'},
   {name: 'Odisha', id: 'Odisha'},
   {name: 'Punjab', id: 'Punjab'},
   {name: 'Rajasthan', id: 'Rajasthan'},
   {name: 'Sikkim', id: 'Sikkim'},
   {name: 'Tamil Nadu', id: 'TamilNadu'},
   {name: 'Telangana', id: 'Telangana'},
   {name: 'Tripura', id: 'Tripura'},
   {name: 'Uttar Pradesh', id: 'UttarPradesh'},
   {name: 'Uttarakhand', id: 'Uttarakhand'},
   {name: 'West Bengal', id: 'West Bengal'},
]